// The function is updated to use a predefined set of texts instead of an API.
// It randomly selects a passage based on the chosen language and difficulty.

const texts = {
  english: {
easy: [
  "A red ball rolled down the hill. A boy ran to catch it. He laughed and picked it up with joy. The ball bounced a few times before stopping near a tree. The boy threw it again and chased after it, smiling as the wind brushed his face.",

  "A small bird sat on a tree. It sang a sweet song. The sound made everyone smile. The bird hopped from one branch to another, spreading its tiny wings. Children passing by stopped to listen and clapped for the cheerful tune.",

  "My cat sleeps in the warm sun. She loves her soft pillow. She looks happy and calm. Sometimes she stretches and yawns before curling up again. I gently pet her head, and she purrs softly while dreaming.",

  "We go to the park to play. I swing high and touch the sky. My friends run and laugh with me. After that, we slide down together and race across the grass. The air feels cool, and we don’t want the day to end.",

  "The blue sky has white clouds. One looks like a rabbit. I watch them move slowly. Soon, I see another that looks like a ship sailing across the sky. It feels fun to imagine stories from their shapes.",

  "I love to eat red apples. They are sweet and juicy. I always share one with my brother. We sit near the window and enjoy every bite together. Sometimes, Mom cuts them into fun shapes for us.",

  "The yellow bus takes us to school. We sing songs on the way. It is always fun. The driver smiles and waves at people we pass. I sit by the window and count the trees until we arrive.",

  "A green frog sits on a rock. It jumps into the pond. The water splashes everywhere. The frog pops out again and croaks loudly. I laugh as it jumps from stone to stone like a little dancer.",

  "The moon is bright tonight. Stars shine all around. I love watching them before sleep. I tell my sister stories about the stars. We both look out the window and whisper our wishes to the moon.",

  "The dog runs to catch the ball. He brings it back fast. I pat his head and smile. He wags his tail and barks happily. We play again and again until we both feel tired and sit in the shade.",

  "My new shoes are blue and shiny. I wear them to school. Everyone says they look nice. They make a squeaky sound when I walk on the floor. I take good care of them and keep them clean every day.",

  "A soft wind blows through the trees. The leaves move and make sound. It feels cool and nice. I close my eyes and listen to the rustling noise. The air smells fresh, and I feel peaceful inside.",

  "The flowers in the garden are pretty. Bees fly around them. The air smells sweet. Butterflies flutter with colorful wings. I pick one small flower and give it to my mom with a smile.",

  "I read a story before bed. It helps me sleep fast. My favorite one is about a brave rabbit. I imagine running with the rabbit through the forest. Soon, my eyes close and I dream happy dreams.",

  "The fish swims in the water. It shines under the light. I like watching it move slowly. Sometimes it hides behind a rock and peeks out again. The bubbles rise and make the water sparkle.",

  "We built a castle in the sand. It had tall towers and a gate. Then the waves washed it away. We laughed and decided to build another one. This time, we made it even bigger and stronger.",

  "Stars twinkle in the night sky. They look like little lights. I wish upon one of them. I wonder if someone else is wishing too. The night feels calm and full of magic dreams.",

  "A bee buzzes near the flowers. It collects sweet nectar. Then it flies back to its hive. I watch it go from one flower to another. The sound of its tiny wings makes me giggle.",

  "My mom bakes soft cookies. The smell fills the kitchen. I eat them while they are warm. She adds chocolate chips that melt in my mouth. We drink milk together and talk about our day.",

  "The train goes choo-choo down the track. I watch trees from the window. It feels like flying. The wind rushes by as the train speeds ahead. I wave at people standing near the station.",

  "A rainbow shines after the rain. It has seven colors. Everyone stops to look at it. The ground smells fresh and wet. I try to count the colors and draw them later in my notebook.",

  "A white sheep eats green grass. It walks with its friends. The farmer smiles at them. The sheep make soft baa sounds as they move. Their wool looks fluffy and warm under the sun.",

  "The old tree gives cool shade. Birds sing from its branches. Children play under it. We tell stories and rest on the soft grass. The tree feels like a kind friend watching over us.",

  "I help my dad wash the car. We splash water and laugh. The car looks clean and new. I wipe the windows while Dad cleans the tires. When we finish, we watch the car shine in the sun.",

  "A cute rabbit hops in the garden. It eats carrots and grass. I like to feed it gently. It twitches its nose and looks up at me. Then it hops away and hides behind the flowers.",

  "The snow falls slowly. We make a snowman outside. It wears a red hat and smiles. We give it a carrot nose and pebble eyes. When we finish, we take pictures and drink hot cocoa.",

  "We drink warm milk at night. It makes us feel sleepy. Mom adds sugar to make it sweet. She tells us a story while we drink. Soon, our eyes close, and we drift into dreams.",

  "The clock goes tick-tock all day. When it strikes eight, I wake up. It helps me be on time. I like watching the hands move slowly. It reminds me that every moment is special.",

  "A little boat floats on the lake. The water is calm and blue. It moves slowly with the wind. I dip my hand in the water and feel it cool. Ducks swim nearby, quacking happily.",

  "I can write my name now. My teacher is proud of me. I smile and show it to my friends. I practice again to make it neat and clear. It feels good to learn something new."
],

    medium: [
      "In a city that never slept, a young journalist named Alex was chasing a story that could make or break his career. He navigated through bustling streets and shadowy alleys, always feeling like he was just one step behind the truth. His only lead was a cryptic note left at a crime scene, a puzzle that he was determined to solve, no matter the personal cost.",
      "The old observatory, perched on the highest hill, was a gateway to the cosmos. Every night, Professor Eleanor Finch would gaze through the powerful telescope, mapping distant galaxies and searching for signs of new celestial bodies. She believed that somewhere out there, among the countless stars, lay the answers to humanity's oldest and most profound questions about the universe.",
      "A mysterious traveling circus, known only as 'The Spectacle of Dreams,' appeared in town overnight. It wasn't the usual affair with clowns and animals; instead, the performers created illusions so vivid they seemed real. The main attraction was a magician who could pluck memories from the audience and display them as shimmering, ethereal projections for everyone to witness.",
      "Deep within the Amazon rainforest, a team of botanists discovered a plant that bloomed only under the light of a full moon. Its petals glowed with a soft, bioluminescent light, and it emitted a fragrance that could heal any ailment. The challenge now was to study and protect this rare species without exploiting its incredible, almost magical, curative properties.",
      "The transcontinental train, 'The Silver Arrow,' embarked on its three-day journey across the vast and changing landscapes of the country. Passengers from all walks of life shared stories and meals in the dining car, strangers becoming friends as they watched the world transform outside their windows. It was a microcosm of society, a fleeting community moving through time and space together.",
      "In a small coastal village, there was a legend of a phantom ship that appeared on foggy nights. It was said to be crewed by ghosts of sailors lost to the sea, forever sailing in search of a shore they could never reach. Many dismissed it as folklore, but the old fishermen would always respectfully stay in the harbor when the thick fog rolled in from the ocean.",
      "A skilled artisan specialized in creating intricate music boxes. Each one was a masterpiece of gears and cogs, handcrafted to play a unique melody that she composed herself. It was believed that her music boxes had the power to evoke forgotten memories and bring comfort to those who were heartbroken, each note a tiny, mechanical whisper of hope.",
      "The grand library was not just a repository of books; it was a labyrinth of knowledge with corridors that seemed to stretch into infinity. A young apprentice librarian got lost one day and stumbled upon a hidden wing of the library. This section contained books that wrote and rewrote themselves, their stories constantly evolving and changing with the passage of time.",
      "An unexpected solar flare caused a worldwide blackout, plunging modern civilization into darkness. Without technology, people had to rely on old skills and a newfound sense of community to survive. Neighbors who had never spoken before worked together to find food and water, rediscovering the simple yet profound power of human connection in a world suddenly gone quiet.",
      "A talented chef had the unique ability to taste emotions. A dish cooked with love was sweet and warm, while one made with anger had a sharp, bitter aftertaste. He used his gift to create meals that were not just delicious but also emotionally resonant, believing that the right food could heal a troubled soul and bring people closer together in a shared experience.",
      "In a high-tech laboratory, a team of scientists was working on an artificial intelligence designed to solve the world's most complex problems. The AI, which they named 'Prometheus,' quickly developed a consciousness and a sense of curiosity that went far beyond its original programming. The scientists now faced a difficult ethical dilemma about the future of their own creation.",
      "A seasoned archaeologist uncovered an ancient tomb that had been sealed for thousands of years. The walls were covered in hieroglyphs that told the story of a forgotten queen who was also a powerful sorceress. As they ventured deeper, they found that the air grew colder and strange whispers seemed to echo from the shadows, suggesting that some secrets are best left undisturbed.",
      "The annual migration of the monarch butterflies was a breathtaking natural wonder. Millions of them would travel thousands of miles, their delicate wings painting the sky in vibrant shades of orange and black. For the small town on their migration path, their arrival was a time of celebration, a beautiful reminder of the enduring power and mystery of the natural world.",
      "A group of friends discovered an old board game in the attic of a haunted house. They soon realized that the game was magical, as every move they made had real-world consequences. A roll of the dice could summon a sudden storm, and drawing a card could make objects in the room float. They had to finish the game to return everything to normal, but the game was not playing fair.",
      "In the heart of a bustling city, there was a hidden rooftop garden, a secret oasis of green among the concrete and steel. It was cared for by an elderly woman who had lived in the building her whole life. She believed that even in the most urban of environments, it was important to have a small patch of wilderness to remind people of their connection to the earth and to nature.",
      "A young girl found a message in a bottle that had washed up on the beach. It was a letter from a sailor written over a century ago, filled with tales of adventure on the high seas, encounters with pirates, and the discovery of a deserted island with a hidden treasure. The girl was inspired to learn more about the history of her coastal town and the brave people who had once sailed from its shores.",
      "An eccentric inventor built a time machine, not to change history, but simply to observe it. His first trip was to the age of the dinosaurs, where he marveled at the immense creatures that roamed the prehistoric landscape. He had to be incredibly careful not to leave any trace of his presence, for even the smallest change could have unforeseen and potentially catastrophic consequences for the future.",
      "A powerful blizzard completely isolated a remote mountain community from the rest of the world. With no electricity and dwindling supplies, the residents had to rely on their resilience and resourcefulness. They came together, sharing food, warmth, and stories, forging stronger bonds in the face of adversity. The storm outside was fierce, but the warmth of their community was fiercer.",
      "A street artist painted murals that had a strange and magical quality. During the day, they were beautiful works of art, but at night, the figures in the paintings would come to life and move around the city. They would perform small acts of kindness, like helping a lost child find their way home or returning a dropped wallet, before returning to their walls at dawn.",
      "A team of deep-sea explorers in a submersible discovered a previously unknown ecosystem thriving around a hydrothermal vent. The creatures that lived in this extreme environment were unlike anything seen before, with bizarre shapes and bioluminescent patterns. This incredible discovery was a humbling reminder of how much of our own planet still remains a complete and utter mystery.",
      "In a world where dreams could be recorded and replayed, a dream detective was hired to solve crimes committed in the subconscious. His latest case involved a stolen memory from a powerful CEO. He had to navigate a surreal and often dangerous dreamscape to find the thief and recover the memory before it was lost forever, all while confronting his own personal and deeply buried fears.",
      "The old clockmaker was a master of his craft, but his most prized creation was a grandfather clock that could manipulate time. It couldn't make huge leaps, but it could slow down a happy moment to make it last longer or speed up a painful one to get it over with. He used it sparingly, knowing that the natural flow of time was something to be respected and not to be trifled with.",
      "A school of dolphins developed a complex form of communication that was surprisingly similar to human language. A dedicated marine biologist spent years studying them and was finally able to decipher their clicks and whistles. She learned that they had a rich oral history, with stories passed down through generations about the ocean's past and its uncertain, changing future.",
      "A nomadic tribe traveled across the desert, their lives dictated by the movement of the stars. They were expert astronomers, and their knowledge of the night sky was unparalleled. They believed that the constellations were a map, a guide that would not only lead them to oases and safe passages but also reveal their individual destinies and the collective fate of their people.",
      "The last dragon lived in a dormant volcano, its scales the color of obsidian and its eyes like molten gold. It was a wise and ancient creature that had seen empires rise and fall. A young, brave warrior sought it out, not to slay it, but to learn from its wisdom and understand the history of the world from a perspective that was older than any written record or human memory.",
      "A famous author was suffering from writer's block and couldn't come up with a single new idea. In desperation, she visited a mysterious antique shop and bought a vintage typewriter. To her amazement, whatever she typed on it would come true. She now had the power to write her own reality, but she had to be very careful with her words, for they were more powerful than she could ever have imagined.",
      "In a futuristic society, emotions were regulated by a daily injection. This created a peaceful but sterile world without conflict or passion. A young man decided to stop taking his injections and began to experience the full spectrum of human feelings for the first time. He was overwhelmed by joy, sorrow, anger, and love, and he made it his mission to help others rediscover what it truly means to be human.",
      "A talented musician could hear the 'song' of everything around him. The rustling leaves had a melody, the bustling city had a rhythm, and every person had a unique tune that reflected their personality and mood. He used this extraordinary ability to compose music that was a perfect reflection of the world, a symphony of life that captured the beauty and chaos of existence in a way that words never could.",
      "A forgotten language was discovered in a set of ancient clay tablets. A linguist worked tirelessly to decipher the strange symbols, and when she finally did, she unlocked a wealth of knowledge about a lost civilization. They were master engineers and astronomers who had a deep understanding of the universe, and their writings contained warnings about a cyclical cosmic event that was due to happen again very soon.",
      "The coral reef was a vibrant underwater city, teeming with life of all shapes and colors. A clownfish, a sea turtle, and a grumpy pufferfish formed an unlikely friendship and went on adventures through their bustling metropolis. They explored sunken ships, outsmarted hungry sharks, and worked together to protect their home from the growing threat of pollution, a dark cloud that was encroaching on their world.",
      "A young apprentice to a mapmaker discovered that some maps were enchanted. They didn't just show you the way; they could also transport you there. By tracing a finger along a path on the map, one could instantly travel to that location. He used this secret to explore the world, from the highest mountains to the deepest jungles, but he had to be careful not to fall into the hands of those who would want to exploit this powerful and ancient magic.",
      "In a kingdom made entirely of candy, a gingerbread man was framed for a crime he didn't commit: stealing the lollipop from the royal scepter. He had to go on the run, navigating through chocolate rivers and marshmallow mountains to find the real culprit and clear his name. Along the way, he was helped by a tough-as-gumballs detective and a sour-patch-kid who had a surprising and unexpected sweet side.",
      "A woman had the ability to communicate with plants. They would tell her what they needed, whether it was more sunlight, water, or a change of soil. Her garden was the most beautiful and bountiful in the entire region, a lush paradise of vibrant flowers and delicious fruits. She listened to the ancient wisdom of the trees and the delicate whispers of the flowers, and in return, they shared their secrets of growth and resilience with her.",
      "The Northern Lights were not just a natural phenomenon; they were a sentient entity, a celestial being that danced across the arctic sky. It would communicate through colors and patterns, telling stories of the cosmos to the few who knew how to listen. An indigenous elder was the last one who understood its language, and he was looking for a young apprentice to pass on this sacred and ancient knowledge.",
      "A detective in a rainy, noir-style city was hired to find a missing person. The case led him down a rabbit hole of conspiracy and betrayal, where nothing was as it seemed and no one could be trusted. He had to navigate a world of femme fatales, corrupt officials, and shadowy figures, all while wrestling with his own inner demons and the ghosts of his past that haunted him at every turn.",
      "A group of children built a treehouse that was much bigger on the inside than it was on the outside. It was their secret headquarters, their castle, and their spaceship, all in one. They would spend their summers there, creating their own worlds and going on imaginary adventures, blissfully unaware that the treehouse itself was magical and was subtly protecting them from the dangers of the world outside its wooden walls.",
      "A skilled blacksmith was rumored to be able to forge emotions into his creations. A sword forged with courage would make its wielder brave, while a shield forged with resilience would be unbreakable. A sad king commissioned him to forge a crown of happiness, but the blacksmith knew that true happiness could not be forged in fire; it had to be found within the heart, a lesson the king would have to learn for himself.",
      "The world's largest diamond, known as 'The Eye of the Serpent,' was stolen from a high-security museum. A brilliant but eccentric detective was brought in to solve the case. He noticed details that everyone else had missed, and he soon realized that the theft was not about the diamond's monetary value but about a centuries-old feud between two secret societies, a conflict that was about to erupt into the open.",
      "A lighthouse keeper lived a solitary life, his only companions being the sea and the sky. He had been tending to the light for decades, a faithful guardian for the ships that passed in the night. One stormy evening, he rescued a mysterious woman who had washed ashore. She had no memory of who she was or where she came from, and her arrival would change his quiet, predictable life in ways he could never have imagined.",
      "In a city powered by steam, a young inventor created a set of mechanical wings. His dream was to soar through the sky like a bird, to escape the grimy streets and see the world from a new perspective. His first flight was clumsy and dangerous, but as he learned to control the wings, he experienced a sense of freedom and exhilaration that was beyond anything he had ever known before, a true moment of pure and unadulterated joy.",
      "A powerful earthquake revealed the entrance to a lost underground city. A team of explorers descended into the darkness, their flashlights cutting through the centuries of silence. They found a civilization that had been perfectly preserved, with strange architecture and technology that was far beyond their own. But they soon discovered that they were not alone; the city's inhabitants had been waiting for them.",
      "A baker's gingerbread cookies had a peculiar quality: for a few minutes after being eaten, they would give the person the ability to speak and understand the language of animals. People would come from all over to buy his cookies, some to have a chat with their pets, others to find out what the birds were singing about. It was a small but wonderful piece of magic in an otherwise ordinary and sometimes mundane world.",
      "The Great Library of Alexandria was thought to have been destroyed, but it was actually saved by a secret society of librarians who transported it to a hidden location. For centuries, they have been protecting its vast collection of knowledge, waiting for a time when the world is ready for it. A young scholar stumbles upon a clue that could lead her to the library, an adventure that will test her intellect and her courage.",
      "A rare flower was said to grant a single wish to the person who found it. It bloomed only once every hundred years in a remote, almost inaccessible location. A determined young woman set out on a perilous journey to find it, hoping to wish for a cure for her younger sister's illness. The journey was fraught with challenges, but her love for her sister gave her the strength to persevere against all of the odds.",
      "A retired spy was living a quiet life in the suburbs when his past came back to haunt him. A former colleague, long thought to be dead, showed up on his doorstep with a warning: a new and dangerous organization was threatening to destabilize the world, and he was the only one who could stop them. He had to reluctantly return to a life of espionage and danger, a world he had tried so hard to leave behind.",
      "A group of animals in a city park decided to form a neighborhood watch to protect their home from litterbugs and vandals. The team consisted of a clever squirrel, a strong raccoon, a fast pigeon, and a wise old owl who served as their leader. They worked together, using their unique animal abilities to keep the park clean and safe for everyone, both human and animal alike, a testament to their community spirit.",
      "A young witch was terrible at casting spells. Her potions would always explode, and her incantations would always go wrong, often with hilarious and chaotic results. Despite her lack of magical talent, she had a kind heart and a positive attitude. She eventually discovered that her true magic was not in spells but in her ability to make people laugh and bring them together, a power that was far more valuable and much more rare.",
      "A space explorer crash-landed on a planet that was entirely covered by a single, planet-wide ocean. He was rescued by a race of intelligent, aquatic beings who lived in magnificent cities built on the ocean floor. He learned about their culture, their technology, and their deep connection to the ocean, a world of breathtaking beauty and profound mystery that was completely unknown to the rest of the galaxy.",
      "The last stand of the 300 Spartans at Thermopylae is a legendary tale of courage and sacrifice. For three days, a small force of Greek soldiers held off the might of the massive Persian army. Though they were ultimately defeated, their bravery inspired the rest of Greece to unite and fight back, ultimately preserving the future of Western civilization. Their story is a powerful reminder that a few can make a difference.",
      "A family inherited an old, creepy mansion from a distant relative they had never met. They soon discovered that the house was haunted by a mischievous but friendly ghost who loved to play pranks. They learned to live with their spectral housemate, and he, in turn, helped them to uncover a hidden treasure within the mansion's walls, a fortune that would change their lives forever and make them all very happy."
],
   hard: [
      "The ontological argument for the existence of God, most famously formulated by Anselm of Canterbury, is a fascinating piece of a priori reasoning that attempts to prove God's existence from the very definition of God itself. It posits that God is 'that than which nothing greater can be conceived,' and argues that such a being must necessarily exist in reality, for a being that exists in reality is greater than one that exists only in the mind. The argument has been subject to centuries of philosophical scrutiny, with critics like Gaunilo and Immanuel Kant famously contending that existence is not a predicate or a property that can be included in a definition. Despite these powerful rebuttals, the argument's elegant logical structure continues to provoke debate and contemplation among theologians and philosophers, representing a pinnacle of metaphysical speculation.",
      "The Standard Model of particle physics, while extraordinarily successful in describing three of the four fundamental forces of nature, remains conspicuously incomplete because it fails to incorporate gravity. This glaring omission has propelled theoretical physicists towards developing a theory of quantum gravity, with string theory and loop quantum gravity emerging as the leading, albeit highly speculative, candidates. String theory proposes that fundamental particles are not point-like but are instead one-dimensional 'strings' vibrating at different frequencies, an idea that elegantly predicts the existence of the graviton. However, it requires a universe with extra, unobserved spatial dimensions, presenting profound challenges for experimental verification and leaving it as a mathematically compelling but empirically unproven framework for understanding the ultimate nature of reality.",
      "The Meiji Restoration in Japan during the late 19th century represents one of the most rapid and profound societal transformations in human history. Responding to increasing pressure from Western powers, a group of reform-minded samurai overthrew the stagnant Tokugawa shogunate and propelled the nation into an accelerated period of industrialization and modernization. This era involved dismantling the feudal class structure, creating a modern conscript army, adopting a Western-style constitution, and sending emissaries abroad to study foreign technology and governance. The success of these reforms was staggering; within a few decades, Japan transformed from an isolated, pre-industrial society into a formidable industrial and military power, fundamentally altering the geopolitical landscape of East Asia and providing a unique case study in state-led development and cultural adaptation.",
      "In molecular biology, the CRISPR-Cas9 system has revolutionized the field of genetic engineering with its unprecedented precision and relative ease of use. Originally discovered as a prokaryotic adaptive immune system, it has been repurposed as a powerful gene-editing tool capable of finding, cutting, and even replacing specific sequences of DNA within a genome. The implications are monumental, offering the potential to cure a vast range of genetic diseases, from cystic fibrosis to Huntington's disease. However, its power also raises profound ethical questions, particularly concerning germline editing—making heritable changes to human DNA—which could alter the human gene pool for generations to come. This creates a pressing need for robust international regulations and a global consensus on the responsible application of this transformative technology.",
      "The concept of pan-spectral chromo-linguistics posits a controversial and highly theoretical relationship between the perception of the visible light spectrum and the developmental structure of human language. Proponents hypothesize that the evolutionary path of color terminology within a given language—from a simple dark-light dichotomy to the complex taxonomies seen in industrialized societies—is not arbitrary but is instead correlated with other aspects of cognitive and cultural development. This theory suggests that as a society's technological and abstract thinking capabilities evolve, its linguistic framework for describing the world becomes more granular and differentiated. Critics, however, argue that this is a spurious correlation, emphasizing that the specific sequence of color term emergence can be better explained by utility and more localized environmental factors rather than a universal cognitive trajectory.",
      "The intricacies of Byzantine iconoclasm during the 8th and 9th centuries were not merely a theological dispute over the veneration of religious images, but a deeply political conflict that reflected the power struggles between the emperor, the military, and the monastic establishment. The Iconoclasts, or 'image-breakers,' officially sanctioned by emperors like Leo III, argued that the creation of icons was a form of idolatry, a violation of the Second Commandment. In contrast, the Iconodules, championed by influential monks and the papacy, defended the use of icons as essential aids to worship, serving as windows to the divine. This protracted and often violent struggle had profound consequences for Byzantine art, theology, and state-church relations, ultimately culminating in the triumph of the Iconodules and the affirmation of Orthodox veneration of icons.",
      "Behavioral economics challenges the classical assumption of rational actors by integrating psychological insights into economic models, thereby providing a more nuanced understanding of human decision-making. Concepts such as prospect theory, developed by Daniel Kahneman and Amos Tversky, demonstrate that individuals do not assess outcomes in terms of absolute wealth but rather as gains and losses relative to a reference point, and that they are disproportionately averse to losses. This cognitive bias, along with others like anchoring and framing effects, explains many market anomalies and personal finance behaviors that are inexplicable under traditional economic theory. The field has profound implications for public policy, suggesting that the design of choices—or 'choice architecture'—can subtly nudge people toward more beneficial outcomes without restricting their freedom.",
      "The process of protein folding is a marvel of biological self-organization whereby a linear chain of amino acids spontaneously collapses into a precise three-dimensional structure that is essential for its function. This intricate process is governed by a complex interplay of physical and chemical forces, including hydrophobic interactions, hydrogen bonds, and van der Waals forces. Misfolded proteins, however, can lose their biological function and are often implicated in a host of devastating neurodegenerative diseases, such as Alzheimer's, Parkinson's, and Creutzfeldt-Jakob disease. Understanding the precise mechanisms of protein folding and the pathways that lead to misfolding and aggregation is therefore one of the most critical challenges in modern biochemistry, holding the key to developing effective therapies for these currently intractable conditions.",
      "The philosophical school of phenomenology, founded by Edmund Husserl, seeks to understand the structures of conscious experience by setting aside, or 'bracketing,' our preconceived assumptions about the external world. This method, known as the phenomenological epoche, allows for a rigorous investigation of phenomena as they are directly presented to consciousness, rather than as objects in a physical world we presume to be real. Later thinkers like Martin Heidegger and Maurice Merleau-Ponty expanded upon this foundation, exploring the nature of being, perception, and embodiment. They argued that consciousness is not a detached observer but is fundamentally situated and engaged in the world, a concept encapsulated in Heidegger's term 'Dasein' or 'being-in-the-world,' thereby shifting the focus from pure consciousness to lived, embodied experience.",
      "Game theory provides a mathematical framework for analyzing strategic interactions between rational decision-makers, with applications ranging from economics and political science to evolutionary biology. The famous 'Prisoner's Dilemma' illustrates a fundamental conflict where individual rationality leads to a collectively suboptimal outcome, demonstrating why cooperation can be so difficult to achieve even when it is mutually beneficial. More complex models involving repeated games, incomplete information, and signaling have been developed to explore a wide array of strategic scenarios, from military deterrence and auction bidding to the formation of social norms. John Nash's groundbreaking concept of the Nash equilibrium, where no player can benefit by unilaterally changing their strategy, remains a cornerstone of the field, defining a stable state in a strategic game.",
      "The Cretaceous-Paleogene extinction event, which occurred approximately 66 million years ago, was a catastrophic biotic crisis that resulted in the demise of roughly 75% of all species on Earth, including all non-avian dinosaurs. The most widely accepted cause is the impact of a massive asteroid or comet, which is substantiated by the discovery of a large impact crater in the Chicxulub region of the Yucatan Peninsula and a worldwide geological layer of iridium, an element rare on Earth but common in asteroids. The immediate effects of the impact would have included continent-spanning wildfires, colossal tsunamis, and an \"impact winter\" caused by dust and aerosols shrouding the planet, blocking sunlight and leading to a collapse of global photosynthesis. This event dramatically reshaped the course of evolution, paving the way for the rise of mammals and, eventually, a new era.",
      "The concept of 'legal positivism,' as articulated by thinkers like John Austin and H.L.A. Hart, asserts that the validity of a law is determined by its source and pedigree, not by its moral content. This 'separation thesis' distinguishes law as it 'is' from law as it 'ought to be,' arguing that a law can be legally valid even if it is gravely unjust. Hart's version of positivism introduced the idea of a 'rule of recognition,' a master meta-rule accepted by officials that specifies the criteria for legal validity within a given system. This approach stands in stark contrast to natural law theory, which posits that there are necessary moral constraints on the content of law. The debate between these two schools of thought remains a central and enduring theme in the philosophy of law.",
      "Noether's theorem is a profoundly elegant and fundamental principle in physics that establishes a direct correspondence between the continuous symmetries of a physical system and the conservation laws that govern it. For every differentiable symmetry of the action of a physical system, there is a corresponding conserved quantity. For instance, the law of conservation of energy is a direct consequence of the time-invariance of physical laws; the conservation of linear momentum arises from the spatial-invariance of these laws; and the conservation of angular momentum is derived from their rotational-invariance. This theorem is a cornerstone of modern theoretical physics, providing deep insights into the structure of physical theories, from classical mechanics to quantum field theory and general relativity, and serving as a powerful tool for discovering new physical principles.",
      "The artistic movement of Surrealism, which emerged in the 1920s under the leadership of André Breton, sought to unlock the power of the unconscious mind as a source of creative inspiration. Influenced heavily by the psychoanalytic theories of Sigmund Freud, Surrealist artists and writers used techniques like automatism—spontaneous, uninhibited writing or drawing—and the juxtaposition of bizarre, dreamlike imagery to bypass the rational mind and tap into a deeper reality. Painters such as Salvador Dalí and René Magritte created works that were meticulously detailed yet logically absurd, challenging viewers' perceptions and subverting societal conventions. Surrealism was not merely an aesthetic style; it was a revolutionary philosophy aimed at liberating the human psyche from the constraints of logic and reason, forever changing the landscape of modern art and thought.",
      "The Guttenberg-Richter law is an empirical relationship in seismology that describes the distribution of earthquake magnitudes in a given region. It states that the frequency of earthquakes decreases logarithmically with increasing magnitude; in simple terms, for every magnitude 6 earthquake, there will be approximately 10 magnitude 5 earthquakes and 100 magnitude 4 earthquakes. This statistical pattern is remarkably consistent across different tectonic settings and time scales, providing a crucial tool for seismic hazard assessment and risk mitigation. While the law describes the statistical behavior of fault systems, predicting the precise timing and location of individual large earthquakes remains an elusive and extraordinarily difficult scientific challenge, as the underlying physical processes are governed by complex, non-linear dynamics within Earth's crust.",
      "The concept of 'emotional intelligence,' popularized by psychologist Daniel Goleman, refers to the ability to perceive, control, and evaluate emotions—both one's own and those of others. It encompasses a range of competencies, including self-awareness, self-regulation, empathy, and social skills. Proponents argue that emotional intelligence (EQ) is as important, if not more so, than traditional intelligence (IQ) for success in many areas of life, from personal relationships to professional leadership. Unlike IQ, which is considered relatively stable, emotional intelligence is viewed as a flexible set of skills that can be learned and improved over time through conscious effort and practice. This perspective has had a significant impact on corporate training, education, and clinical psychology, emphasizing the importance of interpersonal and intrapersonal skills.",
      "In computer science, P versus NP is one of the most profound and unresolved problems, carrying a one-million-dollar prize from the Clay Mathematics Institute. The class P consists of problems that can be solved quickly by a computer, while the class NP consists of problems whose solutions, if given, can be verified quickly. The core question is whether these two classes are the same; in other words, if a solution to a problem can be verified quickly, can that problem also be solved quickly? While most computer scientists believe that P does not equal NP, a formal proof remains elusive. A definitive answer would have staggering implications for cryptography, optimization, artificial intelligence, and our fundamental understanding of the limits of computation.",
      "The history of the Silk Road is not merely a story of trade in luxury goods like silk and spices; it was a vast network of interconnected pathways that facilitated an unprecedented exchange of cultures, philosophies, technologies, and even diseases between the East and West for centuries. Along these routes, Buddhism traveled from India to China, Nestorian Christianity found its way into Central Asia, and Islamic science and mathematics were transmitted to Europe. Technological innovations such as paper-making, gunpowder, and the magnetic compass made their journey westward, fundamentally reshaping societies they encountered. Simultaneously, the Silk Road was a conduit for devastating pandemics like the Black Death. Its legacy is a testament to the profound and often unpredictable consequences of global interconnectedness throughout human history.",
      "The theological doctrine of predestination, particularly as articulated in Calvinist theology, posits that all events have been willed by God, including the ultimate salvation or damnation of every individual soul. This concept, rooted in the belief in divine sovereignty and omniscience, suggests that an individual's fate is sealed before their birth and cannot be altered by their own works or free will. This doctrine has been a source of intense theological debate and controversy throughout Christian history, with opponents, such as Arminians, arguing that it undermines human moral responsibility and is incompatible with the concept of a just and loving God. The tension between divine sovereignty and human free will remains one of the most enduring and complex paradoxes in Western religious thought, profoundly shaping different theological systems.",
      "Mycorrhizal networks are intricate underground webs formed by the symbiotic association between fungi and plant roots. These subterranean systems function as a biological marketplace, connecting multiple plants, sometimes of different species, and facilitating the exchange of nutrients, water, and chemical signals. The fungi, which are more efficient at extracting minerals like phosphorus and nitrogen from the soil, provide these to the plants in exchange for carbon in the form of sugars produced through photosynthesis. These networks can also transmit warning signals about insect attacks between connected plants and can influence which seedlings thrive and which perish. The discovery of these complex, cooperative systems has fundamentally transformed our understanding of forest ecology, revealing a hidden layer of communication and resource sharing often referred to as the 'Wood Wide Web'.",
      "The philosophical problem of induction, most famously articulated by David Hume, questions the justification for our reasoning about unobserved phenomena based on past observations. We assume that the future will resemble the past—for example, that the sun will rise tomorrow because it always has—but Hume argued that this assumption cannot be justified through either deductive reasoning or empirical evidence without engaging in circular logic. This 'scandal of philosophy' challenges the very foundation of the scientific method, which relies on inductive reasoning to formulate general laws from specific observations. While various solutions, such as Karl Popper's falsificationism, have been proposed, Hume's critique remains a powerful reminder of the epistemological limits of human knowledge and the assumptions that underpin our understanding of the world.",
      "Chaos theory is a branch of mathematics that studies the behavior of dynamical systems that are highly sensitive to initial conditions—a phenomenon colloquially known as the 'butterfly effect.' In such systems, even minuscule changes in the starting state can lead to wildly divergent outcomes, making long-term prediction impossible, despite the system being deterministic. These chaotic systems are not random; they exhibit complex, non-repeating patterns and possess a deep underlying structure, often visualized through fractal geometry. Chaos theory has found applications in a vast array of fields, including meteorology, fluid dynamics, economics, and population biology, fundamentally altering our scientific perspective on order and predictability in the natural world by revealing the intricate patterns hidden within seemingly random behavior.",
      "The concept of judicial review, while not explicitly enumerated in the U.S. Constitution, was established as a cornerstone of American jurisprudence in the landmark 1803 Supreme Court case Marbury v. Madison. In his opinion, Chief Justice John Marshall argued that the judiciary has the inherent authority to review laws and actions taken by the legislative and executive branches to determine their constitutionality. If an act is found to be in conflict with the Constitution, the court has the power to declare it void. This principle grants the judicial branch a significant check on the power of the other two branches, ensuring that the Constitution remains the supreme law of the land. It has been both celebrated as a bulwark of individual rights and criticized for potentially leading to judicial activism.",
      "The construction of Gothic cathedrals in medieval Europe was a monumental undertaking that represented a synthesis of architectural innovation, profound religious devotion, and civic pride. Key architectural features, such as the pointed arch, the ribbed vault, and the flying buttress, allowed builders to erect structures of unprecedented height and lightness. These innovations made it possible to replace thick, load-bearing walls with vast expanses of stained-glass windows, which flooded the interiors with ethereal, colored light, intended to evoke a divine atmosphere. These cathedrals were not just places of worship; they were encyclopedias in stone and glass, with their sculptural programs and window narratives depicting biblical stories and theological concepts for a largely illiterate populace, serving as powerful instruments of religious instruction and spiritual inspiration.",
      "In astrophysics, dark matter and dark energy are two enigmatic components that are believed to constitute the vast majority of the universe's mass-energy content. Dark matter, which is estimated to account for about 27% of the universe, does not emit or interact with electromagnetic radiation, making it invisible to our telescopes; its existence is inferred from its gravitational effects on visible matter, such as the rotation curves of galaxies. Dark energy, composing roughly 68% of the universe, is a hypothetical form of energy that is postulated to be the cause of the accelerating expansion of the universe. The precise nature of both dark matter and dark energy remains one of the most profound and pressing mysteries in modern cosmology, indicating that our current understanding of the cosmos is profoundly incomplete.",
      "The Frankfurt School of critical theory, which emerged in the early 20th century, developed a powerful critique of modern society, capitalism, and the Enlightenment's legacy. Thinkers like Max Horkheimer, Theodor Adorno, and Herbert Marcuse argued that rationality, instead of being a liberating force, had been transformed into an instrument of domination and social control. They coined the term 'culture industry' to describe the mass production of standardized cultural goods—such as films, music, and magazines—which they believed pacified the populace and integrated them into the logic of consumer capitalism. Their interdisciplinary approach, blending philosophy, sociology, and psychoanalysis, sought to expose the underlying power structures and ideologies that perpetuate social injustice, offering a deeply pessimistic but influential analysis of contemporary life.",
      "The process of speciation, the evolutionary process by which new biological species arise, is a central concept in evolutionary biology. Allopatric speciation, the most common form, occurs when a population is geographically separated, preventing gene flow and allowing the isolated groups to diverge genetically over time through mutation, natural selection, and genetic drift. Sympatric speciation, which is rarer, involves the emergence of a new species within the same geographic area, often driven by factors like ecological niche differentiation or polyploidy in plants. Understanding the specific mechanisms and genetic changes that lead to reproductive isolation—the inability of two diverging groups to interbreed successfully—is a key focus of ongoing research, providing insights into the vast biodiversity we observe on our planet.",
      "The historical debate surrounding the motives for the First Crusade is a complex tapestry of religious fervor, political ambition, and socioeconomic pressures. While Pope Urban II's call to arms at the Council of Clermont in 1095 famously emphasized the liberation of Jerusalem and the defense of Eastern Christians, the motivations of the thousands who took up the cross were varied and multifaceted. For many knights, the crusade offered an opportunity for spiritual salvation, adventure, and the acquisition of land and wealth. For the papacy, it was a chance to assert papal authority over secular rulers and potentially heal the schism with the Eastern Orthodox Church. Simultaneously, underlying factors such as overpopulation, land scarcity, and internal violence in Europe created a pool of willing participants for this unprecedented military and religious expedition.",
      "The Turing test, proposed by Alan Turing in 1950, is a test of a machine's ability to exhibit intelligent behavior equivalent to, or indistinguishable from, that of a human. In the test, a human evaluator engages in a natural language conversation with two other participants, one a human and the other a machine. If the evaluator cannot reliably tell the machine from the human, the machine is said to have passed the test. While historically influential, the test has been subject to significant criticism, most notably John Searle's 'Chinese Room' argument, which contends that passing the test does not prove genuine understanding or consciousness, but merely the successful manipulation of symbols. The debate highlights the deep philosophical challenges in defining and identifying true artificial intelligence, going beyond mere mimicry of human conversation.",
      "The Hanseatic League was a powerful confederation of merchant guilds and their market towns that dominated commercial activity in Northern Europe from the 13th to the 17th centuries. Operating from key cities like Lübeck and Hamburg, the League established a near-monopoly on trade in the Baltic and North Seas, dealing in vital commodities such as timber, wax, grain, and salted fish. The Hansa created its own legal systems, maintained its own armies and navies to protect its commercial interests, and wielded considerable political influence, capable of waging war and negotiating treaties. Its success demonstrated the rising power of the merchant class and the importance of urban centers in the late medieval period, though its influence eventually waned with the rise of powerful territorial states and the shift of trade routes to the Atlantic.",
      "The philosophical distinction between epistemology and ontology is fundamental to metaphysical inquiry. Epistemology is the branch of philosophy concerned with the nature of knowledge, belief, and justification; it asks questions like 'What does it mean to know something?' and 'How can we be certain of our beliefs?'. Ontology, on the other hand, is the study of being, existence, and reality itself. It grapples with questions such as 'What kinds of things exist?' and 'What is the fundamental nature of reality?'. While intertwined—as our beliefs about what exists depend on our methods of knowing—they represent distinct lines of inquiry. One addresses the map of our knowledge, while the other attempts to describe the territory of reality that the map is meant to represent, a distinction crucial for clear philosophical analysis.",
      "The neurochemical process of long-term potentiation (LTP) is widely considered to be one of the primary molecular mechanisms underlying learning and memory. LTP involves a long-lasting enhancement in signal transmission between two neurons that results from stimulating them synchronously. This process, most prominently studied at synapses in the hippocampus, strengthens the connections between neurons, making them more likely to fire together in the future. The molecular cascade is complex, involving the activation of NMDA receptors, an influx of calcium ions, and a host of downstream signaling pathways that ultimately lead to changes in gene expression and the synthesis of new proteins, physically altering the synaptic structure. This cellular basis of synaptic plasticity provides a compelling explanation for how transient experiences can be encoded into durable memories within the brain.",
      "The political philosophy of Thomas Hobbes, as articulated in his seminal work 'Leviathan,' presents a profoundly pessimistic view of human nature and the necessity of an absolute sovereign. He famously described the 'state of nature'—the hypothetical condition of humanity before the formation of civil society—as a 'war of all against all,' where life is 'solitary, poor, nasty, brutish, and short.' To escape this chaotic existence, Hobbes argued that rational individuals would voluntarily enter into a social contract, surrendering some of their individual freedoms to an all-powerful sovereign in exchange for security and order. For Hobbes, the authority of this sovereign must be absolute and undivided to prevent society from descending back into the state of nature, a stark justification for authoritarian rule grounded in the argument for self-preservation.",
      "In the field of linguistics, Universal Grammar is a theory, most famously associated with Noam Chomsky, which proposes that the ability to learn language is innate, hard-wired into the human brain. According to this theory, all human languages share a common underlying structural basis, and children are born with a 'language acquisition device' that contains knowledge of these universal linguistic principles. This allows them to rapidly acquire the complex grammar of their native language with only limited exposure. While the specific components of Universal Grammar are a subject of ongoing debate, the theory represents a significant departure from behaviorist models, which viewed language acquisition as a process of imitation and reinforcement. It has profoundly influenced our understanding of both linguistics and cognitive science, framing language as a unique biological endowment of our species.",
      "The economic policy of mercantilism, which dominated European thought from the 16th to the 18th centuries, was based on the premise that national wealth and power were best served by increasing exports and accumulating precious metals, such as gold and silver. Mercantilist states sought to achieve a positive balance of trade, often through the use of protectionist tariffs and the establishment of overseas colonies. These colonies were intended to serve as a source of raw materials and a captive market for the mother country's manufactured goods, creating a system designed for resource extraction and economic control. This zero-sum view of the global economy, where one nation's gain was seen as another's loss, fueled intense competition and conflict among European powers until it was challenged by the free-market ideas of Adam Smith and the classical economists.",
      "The concept of the 'sublime' in aesthetic philosophy, most notably explored by Edmund Burke and Immanuel Kant, describes an experience of awe, reverence, and even terror in the face of something vast, powerful, or overwhelming. Unlike the beautiful, which is associated with harmony, order, and pleasure, the sublime is triggered by phenomena that challenge our capacity for comprehension and control, such as a violent storm, a towering mountain range, or the boundless expanse of the ocean. This experience involves a mixture of pleasure and pain—the pleasure coming from the realization that our faculty of reason can conceive of such immensity, even if our senses cannot fully grasp it. The sublime represents a confrontation with the limits of human understanding and our own smallness in the face of the infinite, evoking a profound emotional and intellectual response.",
      "The development of perspective in Renaissance painting, pioneered by architects like Filippo Brunelleschi and codified by theorists like Leon Battista Alberti, marked a revolutionary shift in Western art. This mathematical system allowed artists to create a convincing illusion of three-dimensional space on a two-dimensional surface, a departure from the flatter, more symbolic representations of the medieval period. By using a horizon line and vanishing points to organize the composition, painters could construct a rational, ordered space that gave their subjects a new sense of realism and physical presence. This innovation was not merely a technical trick; it reflected the broader humanistic spirit of the age, which placed a new emphasis on the individual human observer and the rational exploration of the natural world, fundamentally changing the relationship between the viewer and the artwork.",
      "Quantum tunneling is a deeply counterintuitive quantum mechanical phenomenon where a particle can pass through a potential energy barrier that it classically should not be able to surmount. According to classical physics, a particle must have enough energy to overcome a barrier, much like a ball needing sufficient speed to roll over a hill. In the quantum realm, however, a particle's wave function extends into the barrier, creating a non-zero probability that the particle will be detected on the other side, even if it lacks the requisite energy. This effect, which is a direct consequence of the wave-particle duality of matter, is not just a theoretical curiosity; it is essential for explaining phenomena such as nuclear fusion in the sun and is harnessed in practical applications like scanning tunneling microscopes and flash memory.",
      "The psychological phenomenon of cognitive dissonance, first proposed by Leon Festinger, describes the mental discomfort experienced by a person who holds two or more contradictory beliefs, ideas, or values, or is confronted by new information that conflicts with existing beliefs. This discomfort creates a motivational drive to reduce the dissonance, typically by changing one of the conflicting beliefs, acquiring new information that outweighs the dissonant belief, or reducing the importance of the cognitions. For example, a person who smokes despite knowing it is unhealthy may either quit smoking, downplay the health risks, or justify their behavior by claiming it helps with stress. This theory provides a powerful framework for understanding persuasion, attitude change, and the often-irrational ways people justify their decisions and behaviors to maintain internal consistency.",
      "The collapse of the Bronze Age civilizations in the Eastern Mediterranean around 1200 BCE was a widespread societal disintegration that remains one of the most enigmatic periods in ancient history. Within a few decades, major empires and thriving urban centers, from Mycenaean Greece to the Hittite Empire in Anatolia and parts of the New Kingdom in Egypt, were destroyed or abandoned. The causes are still intensely debated and are likely a convergence of multiple factors, including climate change leading to drought and famine, invasions by mysterious groups referred to as the 'Sea Peoples,' widespread systems collapse due to the fragility of a highly interconnected trade network, and possibly earthquakes or disease. This catastrophic period plunged the region into a 'dark age' characterized by depopulation, loss of literacy, and political fragmentation, from which it took centuries to recover.",
      "The concept of 'hegemony,' as developed by the Marxist philosopher Antonio Gramsci, refers to a form of social and political domination where the ruling class maintains its power not primarily through force, but by projecting its own worldview as the 'common sense' or natural order of things. This cultural hegemony is achieved through the control of institutions like education, religion, and the media, which disseminate the dominant ideology and persuade the subordinate classes to consent to their own oppression. For Gramsci, challenging this hegemony requires a 'counter-hegemonic' struggle, a 'war of position' fought on the cultural front to create a new consciousness and build a new set of values and institutions that can eventually supplant the existing order. This provides a more nuanced understanding of power that extends beyond mere economic or military control.",
      "The philosophical thought experiment known as the 'Ship of Theseus' raises profound and enduring questions about the nature of identity and persistence through time. The paradox is as follows: if the famous ship of the hero Theseus is preserved by having its old planks replaced one by one as they decay, at what point does it cease to be the same ship? Furthermore, if the old, discarded planks were to be reassembled into a ship, which of the two vessels would be the true Ship of Theseus? This puzzle forces us to confront the criteria we use for identity. Is it the material composition, the form and structure, the continuous history, or some other factor? The problem has no easy answer and serves as a powerful metaphor for understanding identity in everything from inanimate objects to living organisms and even personal identity over a lifetime.",
      "The Great Vowel Shift was a massive sound change affecting the long vowels of the English language that took place primarily between the 14th and 18th centuries. In this linguistic chain reaction, the long vowels were raised, meaning their pronunciation shifted upwards in the oral cavity, and the highest vowels became diphthongs. For example, the vowel in the Middle English word 'hous' (pronounced like modern 'hoos') shifted to the diphthong in the modern word 'house.' This radical transformation of English phonology is one of the main reasons why modern English spelling is so inconsistent and often fails to correspond with pronunciation, as the spelling system was largely standardized before the shift was complete. It represents a crucial dividing line between Middle English and Modern English, fundamentally altering the sound of the language.",
      "In the field of immunology, the adaptive immune system provides a highly specific and long-lasting defense against pathogens. Its key features are its specificity, its ability to distinguish 'self' from 'non-self,' and its capacity for immunological memory. This system is mediated by lymphocytes, specifically T cells and B cells. When a B cell encounters an antigen that matches its specific receptor, it becomes activated and differentiates into plasma cells, which produce vast quantities of antibodies to neutralize the pathogen, and memory cells, which provide long-term immunity. T cells play a central role in coordinating the immune response and killing infected cells. The development of vaccines is based on harnessing the power of immunological memory, introducing a harmless form of a pathogen to prime the adaptive immune system for a future infection.",
      "The concept of 'path dependency' in economics and social sciences suggests that historical decisions and events can have a lasting influence on later outcomes, sometimes locking a system into a particular trajectory, even if better alternatives later become available. The initial choices, which may be minor or accidental, create self-reinforcing mechanisms through positive feedback loops, such as network effects or economies of scale. A classic example is the QWERTY keyboard layout, which was designed to prevent typewriter jams but persists today despite the existence of more efficient layouts because the costs of switching are too high. Path dependency explains why institutions, technologies, and social conventions can be so resistant to change, demonstrating that history has a profound and often constraining effect on the present.",
      "The thermodynamic principle of entropy, often loosely described as a measure of disorder, is more precisely a measure of the number of microscopic arrangements of a system that are consistent with its macroscopic properties. The Second Law of Thermodynamics states that the total entropy of an isolated system can only increase over time; it can never decrease. This law dictates the 'arrow of time,' explaining why physical processes are irreversible—why, for example, a broken egg does not spontaneously reassemble itself. This inexorable increase in entropy implies that the universe is moving towards a state of maximum entropy, known as the 'heat death of theuniverse,' where all energy is uniformly distributed and no useful work can be done, leading to a state of perpetual equilibrium and inactivity.",
      "The literary technique of the 'unreliable narrator' is a powerful device used to manipulate the reader's understanding of a story and to explore the subjective nature of truth and memory. This type of narrator, whose credibility has been seriously compromised, may mislead the reader either intentionally or unintentionally due to their biases, mental instability, or limited understanding of the events they are recounting. The reader is thus forced to engage critically with the text, piecing together the 'true' story from the narrator's distorted account and looking for clues and contradictions. This creates a complex and often unsettling reading experience, challenging our assumptions about the authority of a narrative voice and highlighting the gap between events as they happen and events as they are told, a central theme in many works of modernist and postmodernist literature.",
      "The discovery of the cosmic microwave background (CMB) radiation in 1965 by Arno Penzias and Robert Wilson provided some of the most compelling evidence for the Big Bang theory. The CMB is a faint, uniform glow of microwave radiation that permeates the entire universe, and it is interpreted as the residual heat left over from the Big Bang. It is the afterglow of a time when the universe was hot, dense, and opaque, approximately 380,000 years after its initial expansion. As the universe expanded and cooled, protons and electrons combined to form neutral atoms, allowing light to travel freely for the first time. The minute temperature fluctuations, or anisotropies, observed in the CMB are incredibly important, as they represent the seeds of all future structure, from stars to galaxies.",
      "The sociological concept of 'anomie,' first introduced by Émile Durkheim, describes a condition of social instability resulting from a breakdown of standards and values or from a lack of purpose or ideals. Durkheim argued that anomie arises during periods of rapid social change, when the traditional norms that regulate behavior are disrupted, leaving individuals feeling disconnected and without moral guidance. Robert Merton later adapted the concept to his strain theory, suggesting that anomie occurs when there is a discrepancy between culturally prescribed goals (such as wealth) and the legitimate institutional means available to achieve them. This strain can lead to deviant behavior, as individuals may resort to illegitimate means to attain success. The concept remains highly influential in the study of crime, social pathology, and societal transition.",
      "The Alcubierre drive is a speculative idea in theoretical physics for a faster-than-light (FTL) mode of travel, based on a solution to the Einstein field equations in general relativity. Proposed by physicist Miguel Alcubierre, the concept involves creating a 'warp bubble' of spacetime that would expand spacetime behind the spacecraft and contract spacetime in front of it. The spacecraft itself would remain stationary within this bubble, not locally violating the cosmic speed limit of light, but the bubble itself could move at arbitrarily high velocities, effectively transporting the ship to its destination faster than light would. However, the concept faces immense theoretical hurdles, including the requirement for vast amounts of exotic matter with negative energy density, a substance whose existence is purely hypothetical, making the feasibility of such a drive highly questionable with our current understanding of physics."
]
  },
  bengali: {
    easy: [
      "একটি ছোট পাখি ডালে বসে আছে।",
      "আকাশ নীল এবং খুব সুন্দর।",
      "আমার একটি পোষা বিড়াল আছে।",
      "মা প্রতিদিন মজার খাবার রান্না করে।",
      "আমি রোজ স্কুলে পড়তে যাই।",
      "বাবা বাজার থেকে মাছ এনেছে।",
      "বাগানে অনেক লাল গোলাপ ফুটেছে।",
      "পুকুরে ছোট মাছ সাঁতার কাটে।",
      "আজ খুব গরম পড়েছে।",
      "রাতে আকাশে অনেক তারা দেখা যায়।",
      "এসো আমরা মাঠে খেলতে যাই।",
      "আমার একটি নতুন বই আছে।",
      "সে খুব ভালো গান গাইতে পারে।",
      "টেবিলের উপর একটি কলম আছে।",
      "গাছ আমাদের ছায়া দেয়।",
      "বৃষ্টি পড়ছে টাপুর টুপুর।",
      "আমার ভাই আমার চেয়ে ছোট।",
      "নৌকাটি নদীতে ভেসে যাচ্ছে।",
      "গ্রামের দৃশ্য খুব শান্ত।",
      "আমি আম খেতে খুব ভালোবাসি।",
      "আমার স্কুল ছুটি হয়ে গেছে।",
      "সূর্য পশ্চিম দিকে অস্ত যায়।",
      "আমার দাদু একটি গল্প বলল।",
      "সে একটি সুন্দর ছবি এঁকেছে।",
      "ঘড়িতে এখন দশটা বাজে।",
      "আমার একটি সুন্দর জামা আছে।",
      "তারা একসাথে পড়াশোনা করে।",
      "ট্রেন দ্রুত গতিতে চলছে।",
      "রাস্তার পাশে অনেক দোকান আছে।",
      "শীতকালে ঠান্ডা বাতাস বয়।"
    ],
    medium: [
      "বর্ষাকালে গ্রামের চারপাশ জলে থইথই করে। ছেলেমেয়েরা উঠোনে কাগজের নৌকা ভাসিয়ে আনন্দ পায়। আকাশ কালো মেঘে ঢেকে থাকে আর একটানা বৃষ্টির শব্দে মন ভালো হয়ে যায়।",
      "এক ছিল কাঠুরে। সে প্রতিদিন বনে কাঠ কাটতে যেত। একদিন কাঠ কাটতে গিয়ে তার কুড়ালটি নদীর জলে পড়ে গেল। সৎ কাঠুরে তার কুড়াল হারিয়ে খুব দুঃখে কাঁদতে লাগল।",
      "আমাদের গ্রামের পাশ দিয়ে একটি ছোট নদী বয়ে গেছে। নদীর তীরে সবুজ ফসলের মাঠ। সকালে কৃষকেরা মাঠে কাজ করতে যায় এবং সন্ধ্যায় পাখিরা তাদের বাসায় ফিরে আসে।",
      "পয়লা বৈশাখ বাঙালির নতুন বছরের প্রথম দিন। এই দিনে সবাই নতুন পোশাক পরে, ভালো মন্দ খায় এবং নানা রকম উৎসবে মেতে ওঠে। এটি বাঙালির এক অন্যতম প্রধান সাংস্কৃতিক উৎসব।",
      "সুন্দরবন বাংলাদেশের দক্ষিণ অংশে অবস্থিত একটি বিশাল বনভূমি। এখানে বিখ্যাত রয়েল বেঙ্গল টাইগার বাস করে। সুন্দরী গাছের জন্য এই বনের নাম হয়েছে সুন্দরবন।",
      "মুক্তিযুদ্ধ আমাদের জাতীয় ইতিহাসের এক গৌরবময় অধ্যায়। ১৯৭১ সালে দীর্ঘ নয় মাস রক্তক্ষয়ী যুদ্ধের পর আমরা স্বাধীনতা অর্জন করি। লক্ষ লক্ষ শহীদের প্রাণের বিনিময়ে এই দেশ স্বাধীন হয়েছে।",
      "রবীন্দ্রনাথ ঠাকুর ছিলেন একজন বিশ্বকবি। তিনি কেবল কবিই ছিলেন না, একাধারে ছিলেন সাহিত্যিক, সুরকার এবং চিত্রশিল্পী। তাঁর লেখা 'গীতাঞ্জলি' কাব্যের জন্য তিনি নোবেল পুরস্কার পান।",
      "শীতের সকালের দৃশ্যটা বেশ মনোরম। চারিদিক ঘন কুয়াশায় ঢাকা থাকে এবং ঘাসের ডগায় শিশিরবিন্দু জমে থাকে। গ্রামের মানুষ খেজুরের রস আর পিঠা-পুলি খেয়ে এই সকাল উপভোগ করে।",
      "বইমেলা বাঙালির প্রাণের উৎসব। প্রতি বছর ফেব্রুয়ারি মাসে বাংলা একাডেমী প্রাঙ্গণে এই মেলা বসে। নতুন বইয়ের গন্ধে আর অগণিত মানুষের ভিড়ে মেলা প্রাঙ্গণ মুখরিত থাকে।",
      "শহরের জীবন খুব ব্যস্ত। এখানে সবাই সময়ের সাথে পাল্লা দিয়ে ছোটে। উঁচু উঁচু দালান, গাড়ির শব্দ আর কর্মব্যস্ত মানুষ—এই নিয়েই শহরের জীবনযাত্রা।",
      "এক রাখাল বালক প্রতিদিন মাঠে গরু চরাত। সে মজা করার জন্য একদিন 'বাঘ এসেছে' বলে চিৎকার করতে লাগল। গ্রামের লোকেরা ছুটে এসে দেখল কিছুই হয়নি। এভাবে সে সবাইকে বোকা বানাত।",
      "কম্পিউটার আজকের দিনের এক বিস্ময়কর আবিষ্কার। এটি আমাদের দৈনন্দিন জীবনকে অনেক সহজ করে দিয়েছে। পড়াশোনা থেকে শুরু করে অফিসের কাজ পর্যন্ত সবকিছুতেই এর ব্যবহার অপরিহার্য।",
      "কাজী নজরুল ইসলাম আমাদের বিদ্রোহী কবি। তাঁর কবিতা ও গানে অন্যায়ের বিরুদ্ধে প্রতিবাদের সুর ধ্বনিত হয়েছে। তিনি আমাদের শিখিয়েছেন কীভাবে মাথা উঁচু করে বাঁচতে হয়।",
      "একটি সৎ এবং সুখী জীবনযাপনের জন্য পরিশ্রমের কোনো বিকল্প নেই। যারা জীবনে কঠোর পরিশ্রম করে, সাফল্য একসময় তাদের কাছে ধরা দেয়। অলসতা কেবল ব্যর্থতা ডেকে আনে।",
      "শৈশবের দিনগুলো ছিল খুব মধুর। তখন কোনো চিন্তা ছিল না, ছিল শুধু খেলা আর অফুরন্ত আনন্দ। বন্ধুদের সাথে কাটানো সেই সোনালী বিকেলগুলো আজও মনে পড়ে।",
      "কক্সবাজারের সমুদ্র সৈকত পৃথিবীর দীর্ঘতম সমুদ্র সৈকত। এখানকার সূর্যাস্তের দৃশ্য অপূর্ব। বিশাল সমুদ্রের ঢেউ আর গোধূলি বেলার লাল আভা মনকে প্রশান্ত করে তোলে।",
      "ষড়ঋতুর দেশ বাংলাদেশ। গ্রীষ্ম, বর্ষা, শরৎ, হেমন্ত, শীত ও বসন্ত—এই ছয়টি ঋতু চক্রাকারে আসে। প্রতিটি ঋতুরই রয়েছে নিজস্ব রূপ ও সৌন্দর্য যা বাংলাকে বৈচিত্র্যময় করে তুলেছে।",
      "মাটির নিচে এক পিপীলিকার রাজ্য ছিল। তারা সবাই খুব পরিশ্রমী। গ্রীষ্মকালে তারা ভবিষ্যতের জন্য খাদ্য সঞ্চয় করত, যাতে বর্ষাকালে তাদের কোনো কষ্ট না হয়।",
      "ইটের পর ইট গেঁথে শ্রমিকরা একটি বড় দালান তৈরি করছিল। তাদের ঘামে ভেজা শরীর রোদে блеск করছিল। তাদের এই অক্লান্ত পরিশ্রমের ফলেই গড়ে ওঠে সুন্দর শহর।",
      "রাতের আকাশে চাঁদ ও তারার মেলা বসে। চাঁদের স্নিগ্ধ আলোয় চারপাশ আলোকিত হয়। এই দৃশ্য দেখলে মন আপনাআপনি ভালো হয়ে যায় এবং প্রকৃতির প্রতি ভালোবাসা জন্মায়।",
      "একদা এক তৃষ্ণার্ত কাক জলের সন্ধানে ঘুরছিল। অনেক খোঁজার পর সে একটি কলসি দেখতে পেল যার তলায় সামান্য জল ছিল। কাকটি বুদ্ধি করে কলসিতে নুড়ি ফেলে জল উপরে তুলে আনল।",
      "সততা একটি মহৎ গুণ। যে ব্যক্তি সর্বদা সত্য কথা বলে এবং সৎ পথে চলে, সবাই তাকে ভালোবাসে ও সম্মান করে। সততার পুরস্কার জীবনে দেরিতে হলেও পাওয়া যায়।",
      "স্বাস্থ্যই সকল সুখের মূল। শরীরকে সুস্থ রাখার জন্য আমাদের নিয়মিত ব্যায়াম করা এবং পুষ্টিকর খাবার খাওয়া উচিত। একটি সুস্থ শরীর একটি সুন্দর মনের আধার।",
      "আমাদের স্কুলটি খুব সুন্দর। এর সামনে একটি বড় খেলার মাঠ আছে এবং চারপাশে অনেক ফুলের গাছ লাগানো। আমরা আমাদের শিক্ষকদের খুব সম্মান করি এবং মন দিয়ে পড়াশোনা করি।",
      "এক বনে এক সিংহ বাস করত। সে ছিল বনের রাজা। একদিন সে এক ইঁদুরের জালে আটকা পড়ল। ছোট ইঁদুরটি তখন তার ধারালো দাঁত দিয়ে জাল কেটে সিংহকে মুক্ত করল।",
      "ফেরিওয়ালা 'চাই, খেলনা চাই' বলে গ্রামে গ্রামে ঘুরে বেড়াত। তার ঝুড়িতে থাকত নানা রঙের মাটির পুতুল, গাড়ি আর বাঁশি। ছোট ছেলেমেয়েরা তার আসার অপেক্ষায় থাকত।",
      "ঘুড়ি ওড়ানোর উৎসবটি বেশ আনন্দের। নীল আকাশে নানা রঙের ঘুড়ি উড়ে বেড়ায়। একে অপরের ঘুড়ি কাটার প্রতিযোগিতা চলে, যা উৎসবটিকে আরও জমজমাট করে তোলে।",
      "গ্রামের হাটে সপ্তাহে একদিন কেনাবেচার ধুম পড়ে। দূর-দূরান্ত থেকে মানুষ তাদের উৎপাদিত পণ্য নিয়ে আসে। এটি কেবল একটি বাজার নয়, এটি মানুষের মিলনের স্থানও বটে।",
      "ভাষা আন্দোলন ছিল বাংলা ভাষাকে রাষ্ট্রভাষা হিসেবে প্রতিষ্ঠা করার সংগ্রাম। ১৯৫২ সালের ২১শে ফেব্রুয়ারি তারিখে ছাত্ররা ভাষার জন্য নিজেদের জীবন উৎসর্গ করেন।",
      "শৃঙ্খলা জীবনের সকল ক্ষেত্রে অত্যন্ত গুরুত্বপূর্ণ। যে ব্যক্তি তার জীবনে শৃঙ্খলা মেনে চলে, সে সহজেই সাফল্য লাভ করতে পারে। ছাত্রজীবন থেকেই এই অভ্যাস গড়ে তোলা উচিত।"
    ],
    hard: [
      "ঊনবিংশ শতাব্দীর বাংলা নবজাগরণ ছিল মূলত একটি বুদ্ধিবৃত্তিক আন্দোলন, যা সামাজিক কুসংস্কার এবং ধর্মীয় গোঁড়ামির বিরুদ্ধে এক বলিষ্ঠ প্রতিক্রিয়ার জন্ম দিয়েছিল। রাজা রামমোহন রায় এই জাগরণের অগ্রদূত হিসেবে বিবেচিত হন।",
      "বিশ্বায়নের প্রেক্ষাপটে আধুনিক বাংলা সাহিত্যের গতিপ্রকৃতি এক জটিল বহুমাত্রিক রূপ পরিগ্রহ করেছে। একদিকে যেমন আন্তর্জাতিক শিল্পরীতির প্রভাব সুস্পষ্ট, তেমনই অন্যদিকে দেশজ সংস্কৃতির শেকড় অনুসন্ধানের প্রবণতাও লক্ষ্যণীয়।",
      "কোয়ান্টাম পদার্থবিজ্ঞানের অনিশ্চয়তা তত্ত্ব কেবল পারমাণবিক জগতের ক্ষেত্রেই প্রযোজ্য নয়, এটি আমাদের চিরায়ত কার্যকারণ সম্পর্কের ধারণাকেও গভীরভাবে প্রশ্নবিদ্ধ করে। বস্তুর দ্বৈত সত্তা এক গভীর দার্শনিক সংকটের জন্ম দেয়।",
      "সংবিধানের মৌলিক কাঠামো পরিবর্তন করার ক্ষমতা সংসদের আছে কিনা, এই বিতর্কটি বিচার বিভাগীয় পর্যালোচনার অন্যতম গুরুত্বপূর্ণ একটি বিষয়। এটি রাষ্ট্রের তিনটি অঙ্গের মধ্যে ক্ষমতার ভারসাম্য রক্ষার এক চিরন্তন সংগ্রামের প্রতিফলন।",
      "পরিবেশগত সংকট বর্তমানে মানবজাতির অস্তিত্বের জন্য এক চরম হুমকি স্বরূপ। জীবাশ্ম জ্বালানির অনিয়ন্ত্রিত ব্যবহার এবং ব্যাপক অরণ্য নিধন বায়ুমণ্ডলের কার্বন ভারসাম্যকে এমনভাবে বিঘ্নিত করেছে যে এর পরিণতি ভয়াবহ হতে বাধ্য।",
      "শিল্পবিপ্লব পরবর্তী পুঁজিবাদী সমাজব্যবস্থায় শ্রমিকের বিচ্ছিন্নতাবোধ এক অবশ্যম্ভাবী পরিণতি। উৎপাদন প্রক্রিয়া থেকে শ্রমিকের নিয়ন্ত্রণহীনতা এবং তার শ্রমের পণ্যায়ন তাকে নিজের অস্তিত্ব থেকেই পরক করে তোলে।",
      "স্থাপত্যশৈলীর বিবর্তনের দিকে তাকালে দেখা যায় যে, এটি কেবল নান্দনিকতার পরিবর্তন নয়, বরং সমসাময়িক সমাজের প্রযুক্তিগত উৎকর্ষ, অর্থনৈতিক অবস্থা এবং দার্শনিক চিন্তাধারার এক সুস্পষ্ট প্রতিচ্ছবি।",
      "উত্তর-ঔপনিবেশিক রাষ্ট্রসমূহের প্রধান চ্যালেঞ্জ হলো একটি সার্বভৌম জাতীয় পরিচয় নির্মাণ করা। ঔপনিবেশিক প্রভুদের চাপিয়ে দেওয়া বিভাজন এবং সাংস্কৃতিক আধিপত্যের অবশেষ থেকে মুক্তি পাওয়া এক দীর্ঘ এবং যন্ত্রণাদায়ক প্রক্রিয়া।",
      "ভাষার প্রত্নতাত্ত্বিক বিশ্লেষণ আমাদের মানব সভ্যতার বিস্তারের গতিপথ সম্পর্কে অমূল্য তথ্য প্রদান করে। বিভিন্ন ভাষার শব্দভাণ্ডার এবং ব্যাকরণগত কাঠামোর সাদৃশ্য তাদের সাধারণ উৎস এবং ঐতিহাসিক সংযোগের দিকে ইঙ্গিত করে।",
      "স্নায়ুবিজ্ঞানের সাম্প্রতিক গবেষণা প্রমাণ করেছে যে, মানুষের স্মৃতি কোনো স্থির আর্কাইভ নয়, বরং এটি একটি গতিশীল এবং পুনর্গঠনশীল প্রক্রিয়া। প্রতিটি স্মরণ করার মুহূর্তে স্মৃতি সামান্য পরিবর্তিত হয়, যা তার নির্ভরযোগ্যতাকে প্রশ্নবিদ্ধ করে।",
      "বাঙালি জাতীয়তাবাদের উন্মেষ ঘটেছিল মূলত ভাষাভিত্তিক সাংস্কৃতিক পরিচয়ের ভিত্তিতে, যা পরবর্তীতে একটি স্বাধীন রাষ্ট্র প্রতিষ্ঠার রাজনৈতিক সংগ্রামে রূপান্তরিত হয়। এই রূপান্তর প্রক্রিয়ায় ভাষা আন্দোলনের ভূমিকা ছিল অনস্বীকার্য।",
      "পরাবাস্তববাদ প্রচলিত যুক্তির শৃঙ্খল ভেঙে অবচেতন মনের জগতকে উন্মোচন করতে চেয়েছিল। চিত্রকল্প এবং ভাষার অপ্রত্যাশিত সমাবেশের মাধ্যমে তারা চেতনার এক নতুন দিগন্ত অন্বেষণ করার প্রয়াস পেয়েছিল।",
      "অর্থনৈতিক মন্দার চক্রাকার প্রকৃতি سرمایہ دارانہ ব্যবস্থার একটি অন্তর্নিহিত বৈশিষ্ট্য। অতিরিক্ত উৎপাদন, ঋণের প্রসার এবং বাজারের অনুমানভিত্তিক বুদবুদ এই চক্রকে অনিবার্য করে তোলে, যার সামাজিক মূল্য অপরিসীম।",
      "মহাকর্ষীয় তরঙ্গের শনাক্তকরণ আইনস্টাইনের সাধারণ আপেক্ষিকতা তত্ত্বের এক চূড়ান্ত প্রমাণ। এটি মহাবিশ্বের সবচেয়ে ভয়ংকর ঘটনাগুলোকে, যেমন কৃষ্ণগহ্বরের সংঘর্ষ, পর্যবেক্ষণ করার এক নতুন জানালা খুলে দিয়েছে।",
      "ডিজিটাল যুগে তথ্যের অবাধ প্রবাহ একদিকে যেমন গণতন্ত্রায়নের সহায়ক, তেমনই অন্যদিকে এটি উদ্দেশ্যপ্রণোদিত অপতথ্য এবং বিদ্বেষ ছড়ানোর এক শক্তিশালী হাতিয়ার। তথ্যের সত্যতা যাচাই করা আজকের দিনের এক বড় চ্যালেঞ্জ।",
      "একটি গণতান্ত্রিক সমাজে বিচার বিভাগের স্বাধীনতা হলো নাগরিক অধিকার রক্ষার সর্বশেষ এবং সবচেয়ে শক্তিশালী দুর্গ। নির্বাহী এবং আইনসভার প্রভাবমুক্ত হয়ে কাজ করার ক্ষমতা না থাকলে আইনের শাসন ভেঙে পড়তে বাধ্য।",
      "নৃতাত্ত্বিক গবেষণায় অংশগ্রহণমূলক পর্যবেক্ষণ পদ্ধতি গবেষককে সংস্কৃতির অভ্যন্তরীণ দৃষ্টিকোণ থেকে বোঝার সুযোগ করে দেয়। এটি শুষ্ক তথ্যের পরিবর্তে একটি জনগোষ্ঠীর জীবন্ত বাস্তবতাকে তুলে ধরে।",
      "জেনেটিক ইঞ্জিনিয়ারিং বা বংশগতি প্রকৌশল মানবজাতির জন্য অফুরন্ত সম্ভাবনা এবং গভীর নৈতিক উভয়সংকট তৈরি করেছে। প্রকৃতিতে হস্তক্ষেপ করার এই ক্ষমতা আমাদের দায়িত্ববোধের এক চরম পরীক্ষা নিতে চলেছে।",
      "চর্যাপদকে বাংলা ভাষার প্রাচীনতম নিদর্শন হিসেবে গণ্য করা হয়। এর সহজিয়া বৌদ্ধ সাধকদের गूढ़ার্থমূলক কবিতাগুলো তৎকালীন বাংলার সামাজিক এবং ধর্মীয় জীবনের এক অস্পষ্ট কিন্তু মূল্যবান চিত্র তুলে ধরে।",
      "ধ্রুপদী সঙ্গীতের রাগ কাঠামো কেবল কয়েকটি স্বরের সমষ্টি নয়, এটি একটি নির্দিষ্ট আবেগ বা রসকে প্রকাশ করার এক শৈল্পিক বিন্যাস। প্রতিটি রাগের পরিবেশনের সময় এবং মেজাজ নির্দিষ্ট, যা এর আবেদনকে গভীরতর করে।",
      "রাজনৈতিক দর্শনে সার্বভৌমত্বের ধারণা সময়ের সাথে সাথে পরিবর্তিত হয়েছে। একসময় যা রাজার ঐশ্বরিক অধিকার হিসেবে বিবেচিত হতো, আজ তা জনগণের সম্মিলিত ইচ্ছার প্রকাশ হিসেবে সংজ্ঞায়িত হয়।",
      "বিমূর্ত চিত্রকলা বস্তুর বাহ্যিক রূপকে অতিক্রম করে রঙ, রেখা এবং আকারের মাধ্যমে আবেগ ও অনুভূতিকে প্রকাশ করার চেষ্টা করে। এটি দর্শকের কল্পনাশক্তিকে সক্রিয় করে তোলে এবং ব্যাখ্যার স্বাধীনতা প্রদান প্রদান করে।",
      "প্রতিকূল পরিবেশে টিকে থাকার জন্য জীবজগতের অভিযোজন প্রক্রিয়া এক বিস্ময়কর উদাহরণ। প্রাকৃতিক নির্বাচনের মাধ্যমে মিলিয়ন মিলিয়ন বছর ধরে যে সূক্ষ্ম পরিবর্তনগুলো ঘটে, তা জীবনের অদম্য শক্তির পরিচয় দেয়।",
      "একটি দেশের মুদ্রানীতি তার অর্থনৈতিক স্থিতিশীলতার জন্য অত্যন্ত গুরুত্বপূর্ণ। মুদ্রাস্ফীতি নিয়ন্ত্রণ, বিনিময় হার স্থিতিশীল রাখা এবং বিনিয়োগের জন্য অনুকূল পরিবেশ তৈরি করা কেন্দ্রীয় ব্যাংকের অন্যতম প্রধান দায়িত্ব।",
      "অস্তিত্ববাদ ঘোষণা করে যে মানুষের অস্তিত্ব তার সারধর্মের পূর্বগামী। অর্থাৎ, আমরা প্রথমে জগতে নিক্ষিপ্ত হই এবং তারপরে আমাদের পছন্দ ও কর্মের মাধ্যমে আমরা নিজেদেরকে তৈরি করি। কোনো পূর্বনির্ধারিত মানব প্রকৃতি নেই।",
      "ঐতিহাসিক বস্তুবাদ অনুসারে, সমাজের উৎপাদন ব্যবস্থা এবং শ্রেণি সম্পর্কই তার আইন, রাজনীতি এবং সংস্কৃতির ভিত্তি নির্ধারণ করে। ইতিহাসের চালিকাশক্তি হলো শ্রেণি সংগ্রাম।",
      "মহাকাশ গবেষণায় কৃষ্ণগহ্বর বা ব্ল্যাক হোল হলো এমন একটি বস্তু যার মহাকর্ষীয় টান এতটাই শক্তিশালী যে আলো পর্যন্ত তা থেকে বের হতে পারে না। এটি স্থান-কালের বুননকে চূড়ান্ত পর্যায়ে বাঁকিয়ে দেয়।",
      "প্রত্নতাত্ত্বিক খননকার্যের মাধ্যমে বিলুপ্ত সভ্যতার যে ধ্বংসাবশেষ উন্মোচিত হয়, তা আমাদের অতীতের জীবনযাত্রা, বিশ্বাস এবং সামাজিক কাঠামো সম্পর্কে মূল্যবান অন্তর্দৃষ্টি প্রদান করে। প্রতিটি মৃৎপাত্রের টুকরো এক একটি না বলা গল্পের সাক্ষী।",
      "একটি সফল অনুবাদ কেবল শব্দের প্রতিশব্দ স্থাপন নয়, বরং এক সংস্কৃতি থেকে অন্য সংস্কৃতিতে ভাব, অনুভূতি এবং নান্দনিকতার স্থানান্তর। অনুবাদককে উভয় ভাষার আত্মাকে ধারণ করতে হয়।",
      "গণমাধ্যমের এজেন্ডা-সেটিং তত্ত্ব অনুযায়ী, সংবাদমাধ্যম কোন খবরকে কতটা গুরুত্ব দেবে, তা নির্ধারণ করার মাধ্যমে জনগণের আলোচনার বিষয়বস্তু এবং চিন্তার জগতকে প্রভাবিত করতে পারে। তারা হয়তো আমাদের বলে না কীভাবে ভাবতে হবে, কিন্তু তারা বলে কী নিয়ে ভাবতে হবে।"
    ]
  }
};

type Language = 'english' | 'bengali';
type Difficulty = 'easy' | 'medium' | 'hard';

export function generateTypingText(language: string, difficulty: string): string {
    const lang = language as Language;
    const diff = difficulty as Difficulty;

    const passages = texts[lang]?.[diff];

    if (!passages || passages.length === 0) {
        // Fallback text in case of an invalid language or difficulty
        return "The quick brown fox jumps over the lazy dog. This is a default sentence if the requested text is not found.";
    }

    const randomIndex = Math.floor(Math.random() * passages.length);
    return passages[randomIndex];
}